services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports: 
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

  backend:
    build: 
      dockerfile: backend.dockerfile
    ports: 
      - "8000:8000"
    depends_on:
      - cronjob
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}

  cronjob:
    build: 
      dockerfile: cronjob.dockerfile
    environment:
      - MONGODB_URL=${MONGODB_URL}
    env_file:
      - .env